version: '3.4'

services:
  web:
    image: caddy:2.4.6-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - frontend
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile # Make sure the docker-compose file is in the same folder
      - /src/html:/srv # Make sure the docker-compose file is above the /src folder 
      - $HOME/.local/share/caddy:/data
      - caddy_config:/config
    command: ["--domain", "example.com"]

volumes:
  www:
  caddy_data:
  caddy_config:

networks:
  frontend:
    name: "frontend"